export const plans = [
  {
    name: "Starter",
    planKey: "starter",
    icon: "⚡",
    badge: "Flexible",
    badgeColor: "bg-slate-100 text-slate-600",
    desc: "Small property ke liye perfect",
    monthlyPrice: 499,
    sixMonthPrice: 2499,
    monthlyDisplay: "₹499",
    sixMonthDisplay: "₹2,499",
    sixMonthSaving: "₹495 bachao (1 mahina free!)",
    color: "border-slate-200",
    headerBg: "bg-slate-50",
    buttonStyle: "bg-slate-800 text-white hover:bg-slate-900",
    buttonText: "Shuru Karen",
    popular: false,
    propertiesLimit: 1,
    staffLimit: 1,
    features: [
      { text: "1 Property", included: true },
      { text: "Booking Bot", included: true },
      { text: "Staff Access (1)", included: true },
      { text: "Basic Dashboard", included: true },
      { text: "Email Support", included: true },
      { text: "Revenue Reports", included: false },
      { text: "WhatsApp Integration", included: false },
      { text: "Priority Support", included: false },
    ],
  },
  {
    name: "Growth",
    planKey: "growth",
    icon: "🚀",
    badge: "Most Popular",
    badgeColor: "bg-orange-500 text-white",
    desc: "Badhte business ke liye best",
    monthlyPrice: 999,
    sixMonthPrice: 4999,
    monthlyDisplay: "₹999",
    sixMonthDisplay: "₹4,999",
    sixMonthSaving: "₹995 bachao (1 mahina free!)",
    color: "border-orange-500",
    headerBg: "bg-orange-50",
    buttonStyle: "bg-orange-600 text-white hover:bg-orange-700",
    buttonText: "Abhi Upgrade Karen",
    popular: true,
    propertiesLimit: 5,
    staffLimit: 3,
    features: [
      { text: "5 Properties", included: true },
      { text: "Booking Bot", included: true },
      { text: "Staff Access (3)", included: true },
      { text: "Advanced Dashboard", included: true },
      { text: "Priority Support", included: true },
      { text: "Revenue Reports", included: true },
      { text: "WhatsApp Integration", included: true },
      { text: "Email Automation", included: true },
    ],
  },
  {
    name: "Business",
    planKey: "business",
    icon: "👑",
    badge: "Best Value",
    badgeColor: "bg-purple-600 text-white",
    desc: "Large scale operations ke liye",
    monthlyPrice: 2499,
    sixMonthPrice: 12499,
    monthlyDisplay: "₹2,499",
    sixMonthDisplay: "₹12,499",
    sixMonthSaving: "₹2,495 bachao (1 mahina free!)",
    color: "border-purple-500",
    headerBg: "bg-purple-50",
    buttonStyle: "bg-purple-600 text-white hover:bg-purple-700",
    buttonText: "Business Shuru Karen",
    popular: false,
    propertiesLimit: 999,
    staffLimit: 999,
    features: [
      { text: "Unlimited Properties", included: true },
      { text: "Booking Bot", included: true },
      { text: "Unlimited Staff", included: true },
      { text: "Full Dashboard", included: true },
      { text: "24/7 Priority Support", included: true },
      { text: "Revenue Reports", included: true },
      { text: "WhatsApp Integration", included: true },
      { text: "Custom Integrations", included: true },
    ],
  },
];

// Plan limits helper - backend mein use hoga
export const PLAN_LIMITS: Record<string, { properties: number; staff: number }> = {
  trial:    { properties: 1, staff: 1 },
  starter:  { properties: 1, staff: 1 },
  growth:   { properties: 5, staff: 3 },
  business: { properties: 999, staff: 999 },
  // legacy plan names support
  professional: { properties: 5, staff: 3 },
  enterprise:   { properties: 999, staff: 999 },
};
