export const plans = [
  {
    name: "Starter",
    icon: "⚡",
    desc: "Perfect for small properties",
    monthlyPrice: 999,
    yearlyPrice: 799,
    color: "border-slate-200",
    buttonStyle: "bg-slate-100 text-slate-700 hover:bg-slate-200",
    buttonText: "Get Started",
    popular: false,
    features: [
      "1 Property",
      "50 Beds",
      "Basic Dashboard",
      "Email Support",
      "Standard Reports",
    ],
  },
  {
    name: "Professional",
    icon: "⚡",
    desc: "Best for growing businesses",
    monthlyPrice: 2499,
    yearlyPrice: 1999,
    color: "border-orange-500",
    buttonStyle: "bg-orange-600 text-white hover:bg-orange-700",
    buttonText: "Upgrade Now",
    popular: true,
    features: [
      "5 Properties",
      "250 Beds",
      "Advanced Dashboard",
      "Priority Support",
      "Custom Reports",
      "WhatsApp Integration",
      "Email Automation",
    ],
  },
  {
    name: "Enterprise",
    icon: "👑",
    desc: "For large scale operations",
    monthlyPrice: 5999,
    yearlyPrice: 4799,
    color: "border-slate-200",
    buttonStyle: "bg-slate-100 text-slate-700 hover:bg-slate-200",
    buttonText: "Get Started",
    popular: false,
    features: [
      "Unlimited Properties",
      "Unlimited Beds",
      "White-label Solution",
      "24/7 Phone Support",
      "API Access",
      "Custom Integrations",
      "Dedicated Account Manager",
      "Advanced Analytics",
    ],
  },
];
